config/routes.rb
TechnologyViewer::Application.routes.draw do

  match 'programmingLanguages' => 'page#programmingLanguages', :path => 'programming-languages', :sub => 'best-rated'
  match 'programmingLanguages/technology/:tech' => 'page#technology', :path => 'programming-languages/technology/:tech'
  match 'programmingLanguages/*sub' => 'page#programmingLanguages', :path => 'programming-languages/*sub'

  match 'webFrameworks' => 'page#webFrameworks', :path => 'web-frameworks', :sub => 'best-rated'
  match 'webFrameworks/:tech' => 'page#technology', :path => 'web-frameworks/technology/:tech'
  match 'webFrameworks/*sub' => 'page#webFrameworks', :path => 'web-frameworks/*sub'

  match 'contentManagementSystems' => 'page#contentManagementSystems', :path => 'content-management-systems', :sub => 'best-rated'
  match 'contentManagementSystems/:tech' => 'page#technology', :path => 'content-management-systems/technology/:tech'
  match 'contentManagementSystems/*sub' => 'page#contentManagementSystems', :path => 'content-management-systems/*sub'

  match 'about' => 'page#about'
  match 'help' => 'page#help'
  match 'help/*sub' => 'page#help'
  match 'search' => 'page#search'

  resources :page

   root :to => 'page#overview'

end

app/views/sub/_best-rated.html.erb
<div class="row-fluid show-grid">
	<div class="span6">
		<div class="well">
			<h3 class="left">Total</h3><div class="help" content="In this table the top five best <%= @title %> are ranked, based on all five aspects combined."></div>
			<table class="table table-bordered table-striped">
				<thead>
				    <tr>
						<th></th>
						<th>Technology</th>
						<th>Rating</th>
				    </tr>
			  	</thead>
			  	<tbody>
			  		<% @total = @top_rated.sort_by { |k, v| -v[:total] }.take 5 %>
				    <% @total.each_with_index do |tech, k| %>
				    	<tr>
				    		<td><%= k + 1 %></td>
				    		<td><%= link_to tech[0].to_s.capitalize, "/#{full_category(tech[1][:category])}/technology/#{tech[0]}" %></td>
							<td><%= tech[1][:total] %></td>
							<td width="40%"><div class="progress"><div class="bar" style="width: <%= Float(tech[1][:total]) / Float(@total_total) * 100 %>%;"></div></div></td>
						</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
	<div class="span6">
		<div class="well">
			<h3 class="left">Adoption</h3><div class="help" content="In this table the top five best <%= @title %> are ranked, based on Adoption. This is an indicator of the usage of these technologies. LinkedIn Jobs and Indeed Resumes are used to rate the <%= @title %>."></div>
			<table class="table table-bordered table-striped">
				<thead>
				    <tr>
						<th></th>
						<th>Technology</th>
						<th>Rating</th>
				    </tr>
			  	</thead>
			  	<tbody>
			  		<% @total = @top_rated.sort_by { |k, v| -v[:adoption] }.take 5 %>
				    <% @total.each_with_index do |tech, k| %>
				    	<tr>
				    		<td><%= k + 1 %></td>
				    		<td><%= link_to tech[0].to_s.capitalize, "/#{full_category(tech[1][:category])}/technology/#{tech[0]}" %></td>
							<td><%= tech[1][:adoption] %></td>
							<td width="40%"><div class="progress"><div class="bar" style="width: <%= Float(tech[1][:adoption]) / Float(@total_adoption) * 100 %>%;"></div></div></td>
						</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>
<div class="row-fluid show-grid">
	<div class="span6">
		<div class="well">
			<h3 class="left">Evolution</h3><div class="help" content="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam semper lobortis velit, non pulvinar nisi auctor ac. Nam sapien orci, dictum eget gravida vitae, pretium ut risus. Suspendisse pellentesque arcu vel lacus pretium non ornare dui egestas. Nullam molestie posuere arcu sit amet pharetra. Nam eget erat sem, id fringilla sem. Curabitur ante risus, venenatis et dignissim non, luctus sed dolor."></div>
			<table class="table table-bordered table-striped">
				<thead>
				    <tr>
						<th></th>
						<th>Technology</th>
						<th>Rating</th>
				    </tr>
			  	</thead>
			  	<tbody>
			  		<% @total = @top_rated.sort_by { |k, v| -v[:evolution] }.take 5 %>
				    <% @total.each_with_index do |tech, k| %>
				    	<tr>
				    		<td><%= k + 1 %></td>
				    		<td><%= link_to tech[0].to_s.capitalize, "/#{full_category(tech[1][:category])}/technology/#{tech[0]}" %></td>
							<td><%= tech[1][:evolution] %></td>
							<td width="40%"><div class="progress"><div class="bar" style="width: <%= Float(tech[1][:evolution]) / Float(@total_evolution) * 100 %>%;"></div></div></td>
						</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
	<div class="span6">
		<div class="well">
			<h3 class="left">Knowledge</h3><div class="help" content="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam semper lobortis velit, non pulvinar nisi auctor ac. Nam sapien orci, dictum eget gravida vitae, pretium ut risus. Suspendisse pellentesque arcu vel lacus pretium non ornare dui egestas. Nullam molestie posuere arcu sit amet pharetra. Nam eget erat sem, id fringilla sem. Curabitur ante risus, venenatis et dignissim non, luctus sed dolor."></div>
			<table class="table table-bordered table-striped">
				<thead>
				    <tr>
						<th></th>
						<th>Technology</th>
						<th>Rating</th>
				    </tr>
			  	</thead>
			  	<tbody>
			  		<% @total = @top_rated.sort_by { |k, v| -v[:knowledge] }.take 5 %>
				    <% @total.each_with_index do |tech, k| %>
				    	<tr>
				    		<td><%= k + 1 %></td>
				    		<td><%= link_to tech[0].to_s.capitalize, "/#{full_category(tech[1][:category])}/technology/#{tech[0]}" %></td>
							<td><%= tech[1][:knowledge] %></td>
							<td width="40%"><div class="progress"><div class="bar" style="width: <%= Float(tech[1][:knowledge]) / Float(@total_knowledge) * 100 %>%;"></div></div></td>
						</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>
<div class="row-fluid show-grid">
	<div class="span6">
		<div class="well">
			<h3 class="left">Newsworthiness</h3><div class="help" content="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam semper lobortis velit, non pulvinar nisi auctor ac. Nam sapien orci, dictum eget gravida vitae, pretium ut risus. Suspendisse pellentesque arcu vel lacus pretium non ornare dui egestas. Nullam molestie posuere arcu sit amet pharetra. Nam eget erat sem, id fringilla sem. Curabitur ante risus, venenatis et dignissim non, luctus sed dolor."></div>
			<table class="table table-bordered table-striped">
				<thead>
				    <tr>
						<th></th>
						<th>Technology</th>
						<th>Rating</th>
				    </tr>
			  	</thead>
			  	<tbody>
			  		<% @total = @top_rated.sort_by { |k, v| -v[:newsvalue] }.take 5 %>
				    <% @total.each_with_index do |tech, k| %>
				    	<tr>
				    		<td><%= k + 1 %></td>
				    		<td><%= link_to tech[0].to_s.capitalize, "/#{full_category(tech[1][:category])}/technology/#{tech[0]}" %></td>
							<td><%= tech[1][:newsvalue] %></td>
							<td width="40%"><div class="progress"><div class="bar" style="width: <%= Float(tech[1][:newsvalue]) / Float(@total_newsvalue) * 100 %>%;"></div></div></td>
						</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
	<div class="span6">
		<div class="well">
			<h3 class="left">Sentiment</h3><div class="help" content="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam semper lobortis velit, non pulvinar nisi auctor ac. Nam sapien orci, dictum eget gravida vitae, pretium ut risus. Suspendisse pellentesque arcu vel lacus pretium non ornare dui egestas. Nullam molestie posuere arcu sit amet pharetra. Nam eget erat sem, id fringilla sem. Curabitur ante risus, venenatis et dignissim non, luctus sed dolor."></div>
			<table class="table table-bordered table-striped">
				<thead>
				    <tr>
						<th></th>
						<th>Technology</th>
						<th>Rating</th>
				    </tr>
			  	</thead>
			  	<tbody>
			  		<% @total = @top_rated.sort_by { |k, v| -v[:sentiment] }.take 5 %>
				    <% @total.each_with_index do |tech, k| %>
				    	<tr>
				    		<td><%= k + 1 %></td>
				    		<td><%= link_to tech[0].to_s.capitalize, "/#{full_category(tech[1][:category])}/technology/#{tech[0]}" %></td>
							<td><%= tech[1][:sentiment] %></td>
							<td width="40%"><div class="progress"><div class="bar" style="width: <%= Float(tech[1][:sentiment]) / Float(@total_sentiment) * 10 %>%;"></div></div></td>
						</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>

app/views/sub/_bubbles.html.erb
<div class="well">
	<div id="bubbles">
		<div class="buttons">
			<button class="action" id="selectAspect"><span class="label">Select aspects</span><span class="selectarrow">&#9660;</span></button>
		</div>
		<div class="help-page"><a href="<%= help_path %>/bubbles">Help</a></div>
		<div id="container" class="container">
		    <div id="main" role="main">
		    	<div id="vis"></div>
		    </div>
		</div>
		<div id="legenda"><ul></ul></div>
	</div>
</div>
<script type="text/javascript">
	$(function () {
		var aspectbox = new Selectbox($('#selectboxAspect'),$('#selectAspect'));

		function delay (ms,func){
			setTimeout(func,ms);
		}

		$(document).click(function() {
		    aspectbox.hide();
		});

		$('#selectAspect').click(function(e){
			e.stopPropagation();
			if(aspectbox.selected){
				aspectbox.hide();
			}
			else{
				aspectbox.show();
			}
		});

		$('#selectboxAspect').click(function(e){
			e.stopPropagation();
		});
		
		var unselectedAspects = [];
		window.bubbleOverview;

		function getCheckbox(checkbox){
			$(checkbox).change(function(){
				if(checkbox.checked == true){
					unselectedAspects.splice(jQuery.inArray(checkbox.id, unselectedAspects),1);
					window.bubbleOverview.update(unselectedAspects);
				}
				if(checkbox.checked == false){
					unselectedAspects.push(checkbox.id);
					window.bubbleOverview.update(unselectedAspects);
				}
			});
		}
		var boxes = aspectbox.getCheckboxes();
		for(var i in boxes){
			getCheckbox(boxes[i]);
		}

		render_overview = function(csv) {
			window.bubbleOverview = new BubbleChart(csv, $("#vis").width(), $("#vis").width() * 0.66, "#vis");
			$('#legenda').css('top', $("#vis").width() * 0.33);
			window.bubbleOverview.start();
			window.bubbleOverview.display_group_all();
		};
		d3.csv("/<%= @csv_file %>", render_overview);
	})
</script>

app/views/sub/_compare.html.erb
<div class="well">
	<div class="buttons">
		<button class="action" id="selectAspect"><span class="label">Select aspects</span><span class="selectarrow">&#9660;</span></button>
	</div>
	<div class="help-page"><a href="<%= help_path %>/compare">Help</a></div>
	<div id="parallel">
		<div id="parallelsvg"></div>
	</div>
</div>

<script type="text/javascript">
$(document).ready(function () {
	var aspectbox = new Selectbox($('#selectboxAspect'),$('#selectAspect'));

	function delay (ms,func){
		setTimeout(func,ms);
	}

	$(document).click(function() {
	    aspectbox.hide();
	});

	$('#selectAspect').click(function(e){
		e.stopPropagation();
		if(aspectbox.selected){
			aspectbox.hide();
		}
		else{
			aspectbox.show();
		}
	});

	$('#selectboxAspect').click(function(e){
		e.stopPropagation();
	});
	
	var unselectedAspects = [];

	function getCheckbox(checkbox){
		$(checkbox).change(function(){
			if(checkbox.checked == true){
				unselectedAspects.splice(jQuery.inArray(checkbox.id, unselectedAspects),1);
				window.parallelgraph.update(unselectedAspects);
			}
			if(checkbox.checked == false){
				unselectedAspects.push(checkbox.id);
				window.parallelgraph.update(unselectedAspects);
			}
		});
	}
	var boxes = aspectbox.getCheckboxes();
	for(var i in boxes){
		getCheckbox(boxes[i]);
	}

    window.parallelgraph = new ParallelGraph($('#parallel'), '<%= "/#{@csv_file}" %>');
});

</script>

app/views/sub/_declining.html.erb
<div class="well">
	<h3 class="left">Declining</h3><div class="help" content="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam semper lobortis velit, non pulvinar nisi auctor ac. Nam sapien orci, dictum eget gravida vitae, pretium ut risus. Suspendisse pellentesque arcu vel lacus pretium non ornare dui egestas. Nullam molestie posuere arcu sit amet pharetra. Nam eget erat sem, id fringilla sem. Curabitur ante risus, venenatis et dignissim non, luctus sed dolor. <br/><br/>In elementum arcu molestie ligula vestibulum consequat gravida dui consectetur. Quisque nec mauris nisl. Curabitur sed nisl sem, sit amet pretium mauris. Nullam dignissim porta ante volutpat iaculis. Vivamus sed pharetra lorem. Lorem ipsum dolor sit amet, consectetur adipiscing elit."></div>
	<table class="table table-bordered table-striped">
		<thead>
		    <tr>
				<th></th>
				<th>Technology</th>
				<th>Adoption</th>
				<th>Evolution</th>
				<th>Knowledge</th>
				<th>Newsworthiness</th>
				<th>Sentiment</th>
				<th>Total</th>
				<th>Iterations declining</th>
		    </tr>
	  	</thead>
	  	<tbody>
	  		<% @key = 0 %>
		    <% @declining = @declining_tech.sort_by { |k, v| -v[:decrease] } %>
		    <% @declining.each do |declining| %>
		    	<% if @key < 10 %>
			    	<tr>
			    		<td><%= @key + 1 %></td>
						<td><%= link_to declining[1][:technology].capitalize, "/#{full_category(declining[1][:category])}/technology/#{declining[1][:technology]}" %></td>
						<td><%= declining[1][:adoption] %> 	<span class="change decrease">(-<%= 1 + rand(10) %>%)</span></td>
						<td><%= declining[1][:evolution] %> 	<span class="change decrease">(-<%= 1 + rand(10) %>%)</span></td>
						<td><%= declining[1][:knowledge] %> <span class="change decrease">(-<%= 1 + rand(10) %>%)</span></td>
						<td><%= declining[1][:newsvalue] %> 	<span class="change decrease">(-<%= 1 + rand(10) %>%)</span></td>
						<td><%= declining[1][:sentiment] %> <span class="change decrease">(-<%= 1 + rand(10) %>%)</span></td>
						<td><%= declining[1][:total] %> 	<span class="change decrease">(-<%= declining[1][:decrease] %>%)</span></td>
						<td>
							<% (1...2 + rand(4)).each do |value| %>
								<div class="arrow down"></div>
							<% end %> 
						</td>
					</tr>
				<% end %>
				<% @key = @key + 1 %>
			<% end %>
		</tbody>
	</table>
</div>

app/views/sub/_help-bubbles.html.erb
<h1>Bubbles</h1>
<p>Nam eleifend nibh erat. Vestibulum accumsan risus ac quam dignissim auctor. Ut lacinia, sem et laoreet consectetur, ante libero fermentum nulla, a pretium neque ligula hendrerit justo. Maecenas malesuada euismod elit in sagittis. Ut et pellentesque magna. Vivamus euismod porttitor ante vitae blandit. Proin at sapien non lacus placerat pellentesque non a purus. Morbi vestibulum, elit non mattis consectetur, est libero posuere mauris, quis dignissim purus erat nec quam. In sem velit, condimentum malesuada lobortis eget, malesuada non nibh. Mauris semper consequat dapibus. Morbi ut dapibus augue. Ut felis purus, cursus in lacinia sed, auctor et purus. Maecenas id ligula nec sapien sodales vehicula. Aenean consequat fringilla purus, id tincidunt est vehicula vitae. Nam aliquam velit sit amet augue dapibus laoreet.</p>

<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean quis dolor odio. Phasellus congue hendrerit adipiscing. Curabitur malesuada, tortor cursus molestie aliquet, enim turpis tempus purus, at pellentesque purus felis viverra lacus. Cras velit quam, condimentum non gravida at, bibendum vel ipsum. Nunc tincidunt gravida arcu ut faucibus. Curabitur adipiscing tincidunt scelerisque. Fusce nec justo enim, a facilisis arcu. Aenean mattis tellus arcu, et tincidunt ante. Quisque urna velit, pretium eget vehicula ut, rutrum non purus. Morbi in purus ac ligula tristique porta. Donec et sapien quis turpis sagittis ultricies in eget sem. Integer lacinia hendrerit lorem, eget pellentesque ante lobortis non. Maecenas congue orci quis libero commodo porta. Nunc rutrum mattis est, eu egestas neque eleifend a.</p>

app/views/sub/_help-compare.html.erb
<h1>Comparing</h1>
<p>Nam eleifend nibh erat. Vestibulum accumsan risus ac quam dignissim auctor. Ut lacinia, sem et laoreet consectetur, ante libero fermentum nulla, a pretium neque ligula hendrerit justo. Maecenas malesuada euismod elit in sagittis. Ut et pellentesque magna. Vivamus euismod porttitor ante vitae blandit. Proin at sapien non lacus placerat pellentesque non a purus. Morbi vestibulum, elit non mattis consectetur, est libero posuere mauris, quis dignissim purus erat nec quam. In sem velit, condimentum malesuada lobortis eget, malesuada non nibh. Mauris semper consequat dapibus. Morbi ut dapibus augue. Ut felis purus, cursus in lacinia sed, auctor et purus. Maecenas id ligula nec sapien sodales vehicula. Aenean consequat fringilla purus, id tincidunt est vehicula vitae. Nam aliquam velit sit amet augue dapibus laoreet.</p>

<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean quis dolor odio. Phasellus congue hendrerit adipiscing. Curabitur malesuada, tortor cursus molestie aliquet, enim turpis tempus purus, at pellentesque purus felis viverra lacus. Cras velit quam, condimentum non gravida at, bibendum vel ipsum. Nunc tincidunt gravida arcu ut faucibus. Curabitur adipiscing tincidunt scelerisque. Fusce nec justo enim, a facilisis arcu. Aenean mattis tellus arcu, et tincidunt ante. Quisque urna velit, pretium eget vehicula ut, rutrum non purus. Morbi in purus ac ligula tristique porta. Donec et sapien quis turpis sagittis ultricies in eget sem. Integer lacinia hendrerit lorem, eget pellentesque ante lobortis non. Maecenas congue orci quis libero commodo porta. Nunc rutrum mattis est, eu egestas neque eleifend a.</p>

app/views/sub/_help-timeline.html.erb
<h1>Timeline</h1>
<p>Nam eleifend nibh erat. Vestibulum accumsan risus ac quam dignissim auctor. Ut lacinia, sem et laoreet consectetur, ante libero fermentum nulla, a pretium neque ligula hendrerit justo. Maecenas malesuada euismod elit in sagittis. Ut et pellentesque magna. Vivamus euismod porttitor ante vitae blandit. Proin at sapien non lacus placerat pellentesque non a purus. Morbi vestibulum, elit non mattis consectetur, est libero posuere mauris, quis dignissim purus erat nec quam. In sem velit, condimentum malesuada lobortis eget, malesuada non nibh. Mauris semper consequat dapibus. Morbi ut dapibus augue. Ut felis purus, cursus in lacinia sed, auctor et purus. Maecenas id ligula nec sapien sodales vehicula. Aenean consequat fringilla purus, id tincidunt est vehicula vitae. Nam aliquam velit sit amet augue dapibus laoreet.</p>

<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean quis dolor odio. Phasellus congue hendrerit adipiscing. Curabitur malesuada, tortor cursus molestie aliquet, enim turpis tempus purus, at pellentesque purus felis viverra lacus. Cras velit quam, condimentum non gravida at, bibendum vel ipsum. Nunc tincidunt gravida arcu ut faucibus. Curabitur adipiscing tincidunt scelerisque. Fusce nec justo enim, a facilisis arcu. Aenean mattis tellus arcu, et tincidunt ante. Quisque urna velit, pretium eget vehicula ut, rutrum non purus. Morbi in purus ac ligula tristique porta. Donec et sapien quis turpis sagittis ultricies in eget sem. Integer lacinia hendrerit lorem, eget pellentesque ante lobortis non. Maecenas congue orci quis libero commodo porta. Nunc rutrum mattis est, eu egestas neque eleifend a.</p>

app/views/sub/_rated-technologies.html.erb
<div class="well">
	<h3 class="left">Rated technologies</h3><div class="help" content="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam semper lobortis velit, non pulvinar nisi auctor ac. Nam sapien orci, dictum eget gravida vitae, pretium ut risus. Suspendisse pellentesque arcu vel lacus pretium non ornare dui egestas. Nullam molestie posuere arcu sit amet pharetra. Nam eget erat sem, id fringilla sem. Curabitur ante risus, venenatis et dignissim non, luctus sed dolor."></div>
	<div class="tab-pane" id="table">
		<table class="table table-bordered table-striped tablesorter" id="example">
			<thead>
			    <tr>
					<th>Name</th>
					<th>Adoption</th>
					<th>Evolution</th>
					<th>Knowledge</th>
					<th>Newsworthiness</th>
					<th>Sentiment</th>
					<th>Total</th>
			    </tr>
		  	</thead>
		  	<tbody>
			    <% CSV.foreach("public/#{@csv_file}", :headers => true) do |csv_obj| %>
			    	<tr>
						<td><%= link_to csv_obj['technology'].capitalize, "/#{full_category(csv_obj['category'])}/technology/#{csv_obj['technology']}" %></td>
						<td><%= csv_obj['adoption'] %></td>
						<td><%= csv_obj['evolution'] %></td>
						<td><%= csv_obj['knowledge'] %></td>
						<td><%= csv_obj['newsworthiness'] %></td>
						<td><%= csv_obj['sentiment'] %></td>
						<td><%= csv_obj['total'] %></td>
					</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>

app/views/sub/_rising.html.erb
<div class="well">
	<h3 class="left">Rising</h3><div class="help" content="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam semper lobortis velit, non pulvinar nisi auctor ac. Nam sapien orci, dictum eget gravida vitae, pretium ut risus. Suspendisse pellentesque arcu vel lacus pretium non ornare dui egestas. Nullam molestie posuere arcu sit amet pharetra. Nam eget erat sem, id fringilla sem. Curabitur ante risus, venenatis et dignissim non, luctus sed dolor."></div>
	<table class="table table-bordered table-striped">
		<thead>
		    <tr>
				<th></th>
				<th>Technology</th>
				<th>Adoption</th>
				<th>Evolution</th>
				<th>Knowledge</th>
				<th>Newsworthiness</th>
				<th>Sentiment</th>
				<th>Total</th>
				<th>Iterations rising</th>
		    </tr>
	  	</thead>
	  	<tbody>
	  		<% @key = 0 %>
	  		<% @rising = @rising_tech.sort_by { |k, v| -v[:increase] } %>
		    <% @rising.each do |rising| %>
		    	<% if @key < 10 %>
			    	<tr>
			    		<td><%= @key + 1 %></td>
						<td><%= link_to rising[1][:technology].capitalize, "/#{full_category(rising[1][:category])}/technology/#{rising[1][:technology]}" %></td>
						<td><%= rising[1][:adoption] %> 		<span class="change increase">(+<%= 1 + rand(10) %>%)</span></td>
						<td><%= rising[1][:evolution] %> 	<span class="change increase">(+<%= 1 + rand(10) %>%)</span></td>
						<td><%= rising[1][:knowledge] %> 	<span class="change increase">(+<%= 1 + rand(10) %>%)</span></td>
						<td><%= rising[1][:newsvalue] %><span class="change increase">(+<%= 1 + rand(10) %>%)</span></td>
						<td><%= rising[1][:sentiment] %> 	<span class="change increase">(+<%= 1 + rand(10) %>%)</span></td>
						<td><%= rising[1][:total] %> 		<span class="change increase">(+<%= rising[1][:increase] %>%)</span></td>
						<td>
							<% (1...2 + rand(4)).each do |value| %>
								<div class="arrow up"></div>
							<% end %> 
						</td>
					</tr>
				<% end %>
				<% @key = @key + 1 %>
			<% end %>
		</tbody>
	</table>
</div>

app/views/sub/_timeline.html.erb
<div class="well">
	<div class="buttons">
		<button class="action" id="selectAspect"><span class="label">Select aspects</span><span class="selectarrow">&#9660;</span></button>
	</div>
	<div class="help-page"><a href="<%= help_path %>/timeline">Help</a></div>
	<div id="line"></div>
</div>
<script type="text/javascript">
	$(function () {
		var aspectbox = new Selectbox($('#selectboxAspect'),$('#selectAspect'));

		function delay (ms,func){
			setTimeout(func,ms);
		}

		$(document).click(function() {
		    aspectbox.hide();
		});

		$('#selectAspect').click(function(e){
			e.stopPropagation();
			if(aspectbox.selected){
				aspectbox.hide();
			}
			else{
				aspectbox.show();
			}
		});

		$('#selectboxAspect').click(function(e){
			e.stopPropagation();
		});
	
	    var lineChart;
	    var urlpath = window.location.pathname.split('/');
	    if(urlpath[1]){
	        lineChart = new Highcharts.Chart({
	            chart: {
	                renderTo: 'line',
	                type: 'line',
	                zoomType: 'x'
	            },
	            title: {
	                text: 'Programming Languages developments',
	                x: -20 //center
	            },
	            xAxis: {
	                categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
	                    'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
	            },
	            yAxis: {
	                title: {
	                    text: 'Rating'
	                },
	                plotLines: [{
	                    value: 0,
	                    width: 1,
	                    color: '#808080'
	                }]
	            },
	            tooltip: {
	                formatter: function() {
	                        return '<b>'+ this.series.name +'</b><br/>'+
	                        this.x +': '+ this.y;
	                }
	            },
	            legend: {
	                layout: 'vertical',
	                align: 'right',
	                verticalAlign: 'top',
	                x: -10,
	                y: 100,
	                borderWidth: 0
	            },
	            series: [
		            <% CSV.foreach("public/#{@csv_file}", :headers => true) do |csv_obj| %>
		            	<%= "{ name: '#{csv_obj['technology']}', data: [#{csv_obj['total'].to_f * rand()}, #{csv_obj['total'].to_f * rand()}, #{csv_obj['total'].to_f * rand()}, #{csv_obj['total'].to_f * rand()}, #{csv_obj['total'].to_f * rand()}, #{csv_obj['total'].to_f * rand()}, #{csv_obj['total'].to_f * rand()}, #{csv_obj['total'].to_f * rand()}, #{csv_obj['total'].to_f * rand()}, #{csv_obj['total'].to_f * rand()}, #{csv_obj['total'].to_f * rand()}, #{csv_obj['total'].to_f}]}," %>
		            <% end %>
	            ]
	        });  
	    }   

	    $(window).resize(function() 
		{    
		    lineChart.setSize(
		       $(".span9").width() - 40,
		       $(document).height() * 0.40,
		       false
		    );  
		    lineChart.redraw() 
		});
	});
</script>