config/routes.rb
TechnologyViewer::Application.routes.draw do

  match 'programmingLanguages' => 'page#programmingLanguages', :path => 'programming-languages', :sub => 'best-rated'
  match 'programmingLanguages/technology/:tech' => 'page#technology', :path => 'programming-languages/technology/:tech'
  match 'programmingLanguages/*sub' => 'page#programmingLanguages', :path => 'programming-languages/*sub'

  match 'webFrameworks' => 'page#webFrameworks', :path => 'web-frameworks', :sub => 'best-rated'
  match 'webFrameworks/:tech' => 'page#technology', :path => 'web-frameworks/technology/:tech'
  match 'webFrameworks/*sub' => 'page#webFrameworks', :path => 'web-frameworks/*sub'

  match 'contentManagementSystems' => 'page#contentManagementSystems', :path => 'content-management-systems', :sub => 'best-rated'
  match 'contentManagementSystems/:tech' => 'page#technology', :path => 'content-management-systems/technology/:tech'
  match 'contentManagementSystems/*sub' => 'page#contentManagementSystems', :path => 'content-management-systems/*sub'

  match 'about' => 'page#about'
  match 'help' => 'page#help'
  match 'help/*sub' => 'page#help'
  match 'search' => 'page#search'

  resources :page

   root :to => 'page#overview'

end

app/views/layouts/_container.html.erb
<div id="main_view">
	<div class="container-fluid">
      	<div class="row-fluid">
      		<div class="span3">
	      		<%= render 'layouts/sidebar' %>
	      	</div>
	      	<div class="span9">
		      	<% if params[:sub] == 'bubbles' %>
		      		<%= render 'sub/bubbles' %>
		      	<% end %>
		      	<% if params[:sub] == 'best-rated' %>
		      		<%= render 'sub/best-rated' %>
		      	<% end %>
		      	<% if params[:sub] == 'rising' %>
		      		<%= render 'sub/rising' %>
		      	<% end %>
		      	<% if params[:sub] == 'declining' %>
		      		<%= render 'sub/declining' %>
		      	<% end %>
		      	<% if params[:sub] == 'compare' %>
		      		<%= render 'sub/compare' %>
		      	<% end %>
		      	<% if params[:sub] == 'timeline' %>
		      		<%= render 'sub/timeline' %>
		      	<% end %>
		      	<% if params[:sub] == 'rated-technologies' %>
		      		<%= render 'sub/rated-technologies' %>
		      	<% end %>
	      	</div>
        </div>
    </div>
</div>

app/views/layouts/_footer.html.erb
<hr>

<footer>
<p>Created by: <%= link_to 'Tom Rozendaal', 'http://www.tomrozendaal.nl', :target => "_blank" %> &copy; <%= Date.today.year %></p>
</footer>

app/views/layouts/_header.html.erb
<div id="header">
	<%= link_to "Technology Relevance Model", root_path, :id => "logo" %>
	<div class="buttons">
		<div id="toprow">
			<a href="<%= root_path %>"><button class="action" id="technologyOverview"><span class="label">Home</span></button></a>
			<a href="<%= programmingLanguages_path %>/best-rated"><button class="action blue" id="programmingLanguages"><span class="label">Programming Languages</span></button></a>
		</div> 
		<div id="bottomrow">
			<a href="<%= webFrameworks_path %>/best-rated"><button class="action red" id="webFrameworks"><span class="label">Web Frameworks</span></button></a>
			<a href="<%= contentManagementSystems_path %>/best-rated"><button class="action green" id="contentManagementSystems"><span class="label">Content Management</span></button></a>
		</div>	
	</div>
	<div class="right">
		<form action="/search" method="get" class="well form-search" autocomplete="off">
			<%= @technologies = [] %>
			<% CSV.foreach("public/data/technologies.csv", :headers => true) do |csv_obj| %>
					<% @technologies << "#{csv_obj['technology'].capitalize}" %>
			<% end %>
			<input type="text" name="tech" class="span3" style="margin: 0 auto;" data-provide="typeahead" data-items="4" data-source="[<%= @technologies.map { |i| "\"" + i.to_s + "\"" }.join(",") %>]">
			<button type="submit" class="btn">Search</button>
		</form>
		<a href="<%= about_path %>">About</a>
	</div>
</div>

app/views/layouts/_selectbox.html.erb
<div id="selectboxLang" class="">
	<ul>
		<label for="lang1"><li><input type="checkbox" id="lang1" class="checkbox" checked/>Java</li></label>
		<label for="lang2"><li><input type="checkbox" id="lang2" class="checkbox" checked/>Javascript</li></label>
		<label for="lang3"><li><input type="checkbox" id="lang3" class="checkbox" checked/>PHP</li></label>
		<label for="lang4"><li><input type="checkbox" id="lang4" class="checkbox" checked/>Scala</li></label>
		<label for="lang5"><li><input type="checkbox" id="lang5" class="checkbox" checked/>Ruby</li></label>
	</ul>
</div>

<div id="selectboxAspect" class="">
	<ul>
		<label for="adoption"><li><input type="checkbox" id="adoption" class="checkbox" />Adoption</li></label>
		<label for="evolution"><li><input type="checkbox" id="evolution" class="checkbox" />Evolution</li></label>
		<label for="knowledge"><li><input type="checkbox" id="knowledge" class="checkbox" />Knowledge</li></label>
		<label for="newsworthiness"><li><input type="checkbox" id="newsworthiness" class="checkbox" />Newsworthiness</li></label>
		<label for="sentiment"><li><input type="checkbox" id="sentiment" class="checkbox" />Sentiment</li></label>
	</ul>
</div>

app/views/layouts/_sidebar.html.erb
<div class="well sidebar-nav">
  <ul class="nav nav-list">
    <li id="" class="nav-header"><%= @title %></li>
    <li id="best-rated"><a href="<%= @current_path %>/best-rated">Best rated</a></li>    
    <li id="rising"><a href="<%= @current_path %>/rising">Rising technologies</a></li>
    <li id="declining"><a href="<%= @current_path %>/declining">Declining technologies</a></li>
    <li id="compare"><a href="<%= @current_path %>/compare">Compare aspects</a></li>
    <li id="bubbles"><a href="<%= @current_path %>/bubbles">Bubbles</a></li>
    <li id="timeline"><a href="<%= @current_path %>/timeline">Timeline</a></li>
    <li id="rated-technologies"><a href="<%= @current_path %>/rated-technologies">Rated technologies</a></li>
  </ul>
</div>

<script type="text/javascript">
	$(function () {
		var urlpath = window.location.pathname.split('/');
		$('ul.nav-list li').each(function(){
			if(urlpath[2] == $(this).attr('id')){
				$(this).attr('class', 'active');
			}
		});
	})
</script>

app/views/layouts/_tab_bubble.html.erb
<script>
	$(function () {
		window.bubbleOverview;
		window.bubbleDetail;

		render_overview = function(csv) {
			var height;
			if($('.tab-content').height()){
				height = $('.tab-content').height();
			} else if($('#container').height()){
				height = $('#container').height();
			}
			window.bubbleOverview = new BubbleChart(csv, $(window).width(), height, "#vis");
			window.bubbleOverview.start();
			window.bubbleOverview.display_group_all();
		};
		d3.csv("/<%= @csv_file %>", render_overview);

		render_detail = function(csv) {
			var width = $(window).width() * 0.224;
			window.bubbleDetail = new BubbleChart(csv, width, width / 2, ".sidebar-nav");
			window.bubbleDetail.start();
			window.bubbleDetail.display_group_all();
		};
		d3.csv("/<%= @csv_file %>", render_detail);
	})
</script>

app/views/layouts/_tab_detail.html.erb
<div class="tab-pane" id="detail">
	<div class="row-fluid">
		<div class="span3">
			<div class= "well sidebar-nav">
			</div>
		</div>
		<div class="span9">
			<div class="hero-unit">
				<div id="detailviews">
					<div id="line"></div>
					<div id="parallel">
						<div id="parallelsvg"></div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<script type="text/javascript">
$(document).ready(function () {
    window.parallelgraph = new ParallelGraph($('#parallel'), '<%= "/#{@csv_file}" %>');


});
</script>

app/views/layouts/_tab_overview.html.erb
<div class="tab-pane active" id="overview">
	<div id="container" class="container">
	    <div id="main" role="main">
	    	<div id="vis"></div>
	    </div>
	</div>
</div>

app/views/layouts/_tab_table.html.erb
<div class="tab-pane" id="table">
	<table class="table table-bordered table-striped tablesorter" id="example">
		<thead>
		    <tr>
				<th>Name</th>
				<th>Adoption</th>
				<th>Knowledge</th>
				<th>Sentiment</th>
				<th>Total</th>
		    </tr>
	  	</thead>
	  	<tbody>
		    <% CSV.foreach("public/#{@csv_file}", :headers => true) do |csv_obj| %>
		    	<tr>
					<td><%= link_to csv_obj['technology'].capitalize, "/#{full_category(csv_obj['category'])}/#{csv_obj['technology']}" %></td>
					<td><%= csv_obj['adoption'] %></td>
					<td><%= csv_obj['knowledge'] %></td>
					<td><%= csv_obj['sentiment'] %></td>
					<td><%= csv_obj['total'] %></td>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Technology Relevance Model</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header' %>
	<%= yield %>
	<%= render 'layouts/selectbox' %>
	<%= render 'layouts/footer' %>
</body>
</html>